'use strict';

module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert('Patterns', [
      {
        name: '1',
        image: '1.jpg',
        category_type_id: 1,
        color_count: 1,
        size_type_id: 1,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        name: '2',
        image: '2.jpg',
        category_type_id: 1,
        color_count: 1,
        size_type_id: 1,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        name: '3',
        image: '3.jpg',
        description: 'Толстовка с разрезами по нижнему краю',
        category_type_id: 1,
        color_count: 1,
        size_type_id: 1,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        name: '4',
        image: '4.jpg',
        description: 'Нижний край толстовки с разрезами, асиметричный - спереди короче, сзади длиннее. Рукава и штанины на резинке.',
        category_type_id: 1,
        color_count: 1,
        size_type_id: 1,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        name: '5',
        image: '5.jpg',
        category_type_id: 1,
        color_count: 1,
        size_type_id: 1,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        name: '6',
        description: 'Нижний край толстовки асиметричный - спереди короче, сзади длиннее. На толстовке втачной карман',
        image: '6.jpg',
        category_type_id: 1,
        color_count: 1,
        size_type_id: 1,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        name: '7',
        image: '7.jpg',
        category_type_id: 1,
        color_count: 3,
        size_type_id: 1,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        name: '8',
        image: '8.jpg',
        category_type_id: 1,
        color_count: 3,
        size_type_id: 1,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        name: '9',
        image: '9.jpg',
        category_type_id: 1,
        color_count: 2,
        size_type_id: 1,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        name: '10',
        image: '10.jpg',
        category_type_id: 1,
        color_count: 2,
        size_type_id: 1,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        name: '11',
        image: '11.jpg',
        category_type_id: 1,
        color_count: 1,
        size_type_id: 1,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        name: '12',
        image: '12.jpg',
        category_type_id: 1,
        color_count: 1,
        size_type_id: 1,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        name: '13',
        image: '13.jpg',
        category_type_id: 1,
        color_count: 1,
        size_type_id: 1,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        name: '14',
        image: '14.jpg',
        category_type_id: 1,
        color_count: 1,
        size_type_id: 1,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        name: '15',
        image: '15.jpg',
        category_type_id: 1,
        color_count: 3,
        size_type_id: 1,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        name: '16',
        image: '16.jpg',
        category_type_id: 1,
        color_count: 2,
        size_type_id: 1,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        name: '17',
        image: '17.jpg',
        category_type_id: 1,
        color_count: 1,
        size_type_id: 1,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        name: '18',
        image: '18.jpg',
        category_type_id: 1,
        color_count: 3,
        size_type_id: 1,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        name: '19',
        image: '19.jpg',
        category_type_id: 1,
        color_count: 2,
        size_type_id: 1,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        name: '20',
        image: '20.jpg',
        category_type_id: 1,
        color_count: 1,
        size_type_id: 1,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        name: '21',
        image: '21.jpg',
        category_type_id: 1,
        color_count: 2,
        size_type_id: 1,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        name: '22',
        image: '22.jpg',
        category_type_id: 1,
        color_count: 1,
        size_type_id: 1,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        name: '23',
        image: '23.jpg',
        category_type_id: 1,
        color_count: 1,
        size_type_id: 1,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        name: '24',
        image: '24.jpg',
        category_type_id: 1,
        color_count: 2,
        size_type_id: 1,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        name: '1c',
        image: 'child1.jpg',
        category_type_id: 3,
        color_count: 2,
        size_type_id: 3,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        name: '2c',
        image: 'costume-child.jpg',
        category_type_id: 3,
        color_count: 1,
        size_type_id: 3,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        name: '1m',
        image: 'man1.jpg',
        category_type_id: 2,
        color_count: 1,
        size_type_id: 1,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        name: '2m',
        image: 'man2.jpg',
        category_type_id: 2,
        color_count: 2,
        size_type_id: 1,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        name: '3m',
        image: 'man3.jpg',
        category_type_id: 2,
        color_count: 1,
        size_type_id: 1,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        name: '4m',
        image: 'man4.jpg',
        category_type_id: 2,
        color_count: 1,
        size_type_id: 1,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        name: 'sleep1',
        image: 'sleepwear-woman.jpg',
        category_type_id: 5,
        color_count: 2,
        size_type_id: 1,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        name: 'sleep2',
        image: 'sleep2.jpg',
        category_type_id: 5,
        color_count: 2,
        size_type_id: 1,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        name: 'base1',
        image: 't-shirt.jpg',
        category_type_id: 7,
        color_count: 1,
        size_type_id: 2,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        name: 'crop-top',
        image: 't-shirt2.jpg',
        category_type_id: 7,
        color_count: 1,
        size_type_id: 2,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        name: 'base-m',
        image: 't-shirt-man.jpg',
        category_type_id: 6,
        color_count: 1,
        size_type_id: 2,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
    ], {});
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('Patterns', null, {});
  },
};
