export const ADD_ITEM_TO_BASKET = 'ADD_ITEM_TO_BASKET';
export const GET_ITEMS_INFO = 'GET_ITEMS_INFO';
export const SAGA_GET_ITEMS_INFO = 'SAGA_GET_ITEMS_INFO';
export const INIT_BASKET_TOTAL = 'INIT_BASKET_TOTAL';
export const CLEAR_BASKET = 'CLEAR_BASKET';

