export const INIT_CURRENT_ITEM = 'INIT_CURRENT_ITEM';
export const INIT_CURRENT_ITEM_PRICE = 'INIT_CURRENT_ITEM_PRICE';
export const INIT_CURRENT_ITEM_COUNT = 'INIT_CURRENT_ITEM_COUNT';

export const SAGA_INIT_CURRENT_ITEM = 'SAGA_INIT_CURRENT_ITEM';
export const SAGA_INIT_CURRENT_ITEM_PRICE = 'SAGA_INIT_CURRENT_ITEM_PRICE';
