export const INIT_ORDERS = 'INIT_ORDERS';
export const FULLFILED_ORDERS = 'FULLFILED_ORDERS';
export const COMPLETED_ORDERS = 'COMPLETED_ORDERS';
export const REJECTED_ORDERS = 'REJECTED_ORDERS';
export const PAID_ORDERS = 'PAID_ORDERS';
export const ON_DELIVERY_ORDERS = 'ON_DELIVERY_ORDERS';
export const ALL_ORDERS = 'ALL_ORDERS';
export const CONFIRMED_ORDERS = 'CONFIRMED_ORDERS';
export const IN_PROCESSING_ORDERS = 'IN_PROCESSING_ORDERS';
export const ERR_ORDERS = 'ERR_ORDERS';
export const INIT_ORDER_MESSAGE = 'INIT_ORDER_MESSAGE';

export const SAGA_INIT_ORDERS = 'SAGA_INIT_ORDERS';
