export const LOGGEDIN_USER = 'LOGGEDIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const CLEAR_USER_MESSAGE = 'CLEAR_USER_MESSAGE';
export const SAGA_LOGGEDIN_USER = 'SAGA_LOGGEDIN_USER';
export const ERR_LOGGEDIN_USER = 'ERR_LOGGEDIN_USER';
export const SAGA_REGISTER_USER = 'SAGA_REGISTER_USER';
