export const LOGGEDIN_USER = 'LOGGEDIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const CLEAR_USER_MESSAGE = 'CLEAR_USER_MESSAGE';
export const ERR_LOGGEDIN_USER = 'ERR_LOGGEDIN_USER';
export const EDIT_USER = 'EDIT_USER';

export const SAGA_LOGGEDIN_USER = 'SAGA_LOGGEDIN_USER';
export const SAGA_REGISTER_USER = 'SAGA_REGISTER_USER';
export const SAGA_LOGOUT_USER = 'SAGA_LOGOUT_USER';
export const SAGA_IS_USER_AUTHORIZED = 'SAGA_IS_USER_AUTHORIZED';
export const SAGA_EDIT_USER = 'SAGA_EDIT_USER';
export const SAGA_EDIT_USER_NAME = 'SAGA_EDIT_USER_NAME';
export const SAGA_EDIT_USER_EMAIL = 'SAGA_EDIT_USER_EMAIL';
export const SAGA_EDIT_USER_PASSWORD = 'SAGA_EDIT_USER_PASSWORD';
